// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetStatusData, GetStatusResponses, LogoutData, LogoutResponses, LoginData, LoginResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Root {
    public static getStatus<ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetStatusResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/',
            ...options
        });
    }
    
    public static logout<ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).delete<LogoutResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/login',
            ...options
        });
    }
    
    public static login<ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LoginResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}