// This file is auto-generated by @hey-api/openapi-ts

export type ApiStatus = {
    session: Session;
    time: string;
};

export type Session = {
    _docid?: string;
    created?: string;
    last_access?: string;
};

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusResponses = {
    200: ApiStatus;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};