[package]
name = "delphi_api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
delphi_api_lib = {path = "../delphi_api_lib"}

[build-dependencies]
delphi_api_lib = {path = "../delphi_api_lib"}
serde = "1.0.219"
serde_json = "1.0.140"
